// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Daryl":return img`
.....ffffff.....
....fddddddf....
....fd1dd1df....
....fddddddf....
....fdd22ddf....
.....ffffff.....
...ff999999ff...
..f9999999999f..
..f2f999999f2f..
..f2f999999f2f..
..ff.f9999f.f...
.....f9999f.....
.....f9999f.....
.....f9999f.....
.....f9999f.....
.....ffffff.....
.....f8888f.....
....f888888f....
...f888ff888f...
...f88f..f88f...
...f8f....f8f...
...ff......ff...
................
................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
